import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:twitter_auth_clone/constant/gaps.dart';
import 'package:twitter_auth_clone/constant/sizes.dart';
import 'package:twitter_auth_clone/features/onboarding/widgets/interest_detail_button.dart';

const Map<String, List<String>> interestDetails = {
  "Daily Life": [
    "Morning Routine",
    "Work Commute",
    "Cooking",
    "Exercise",
    "Family Time",
    "Pet Care",
    "House Chores",
    "Shopping",
    "Socializing",
    "Relaxing",
    "Gardening",
    "Reading",
    "Writing",
    "Watching TV",
    "Playing Games",
    "Hobbies",
    "Personal Development",
    "Budgeting",
    "Traveling",
    "Photography",
    "Blogging",
    "Vlogging",
    "Cleaning",
    "Organizing",
    "Laundry",
    "Childcare",
    "DIY Projects",
    "Meditation",
    "Volunteering",
    "Networking"
  ],
  "Comedy": [
    "Stand-up Comedy",
    "Satire",
    "Sketch Comedy",
    "Improv Comedy",
    "Parody",
    "Slapstick",
    "Dark Comedy",
    "Romantic Comedy",
    "Sitcoms",
    "Comedy Films",
    "Comedy Shows",
    "Funny Clips",
    "Pranks",
    "Comedy Podcasts",
    "Comedy Skits",
    "Comic Strips",
    "Political Comedy",
    "Observational Comedy",
    "Character Comedy",
    "Musical Comedy",
    "Surreal Comedy",
    "Alternative Comedy",
    "Physical Comedy",
    "Mockumentary",
    "Internet Memes",
    "Comedy Competitions",
    "Roast Comedy",
    "Comedy Reviews",
    "Stand-up Specials",
    "Comedy Tours"
  ],
  "Entertainment": [
    "Movies",
    "TV Shows",
    "Music",
    "Books",
    "Theater",
    "Concerts",
    "Festivals",
    "Gaming",
    "Celebrities",
    "Interviews",
    "Red Carpet Events",
    "Reality Shows",
    "Talent Shows",
    "Award Shows",
    "Behind the Scenes",
    "Entertainment News",
    "Talk Shows",
    "Web Series",
    "Cartoons",
    "Anime",
    "Streaming Services",
    "Music Videos",
    "Documentaries",
    "Stand-up Comedy",
    "Magic Shows",
    "Circus",
    "Nightlife",
    "Fan Theories",
    "Movie Trailers",
    "Live Performances"
  ],
  "Animals": [
    "Wildlife",
    "Pets",
    "Birds",
    "Reptiles",
    "Aquatic Animals",
    "Insects",
    "Mammals",
    "Animal Rescue",
    "Animal Training",
    "Animal Behavior",
    "Veterinary Care",
    "Animal Shelters",
    "Zoos",
    "Safaris",
    "Animal Conservation",
    "Pet Adoption",
    "Endangered Species",
    "Animal Welfare",
    "Marine Biology",
    "Ornithology",
    "Herpetology",
    "Pet Care Tips",
    "Exotic Pets",
    "Animal Breeds",
    "Pet Nutrition",
    "Pet Grooming",
    "Animal Photography",
    "Animal Videos",
    "Pet Products",
    "Animal Rights"
  ],
  "Food": [
    "Recipes",
    "Cooking Tips",
    "Baking",
    "Grilling",
    "Healthy Eating",
    "Vegan Recipes",
    "Vegetarian Recipes",
    "Desserts",
    "Snacks",
    "Appetizers",
    "Main Courses",
    "Side Dishes",
    "Beverages",
    "Cocktails",
    "Smoothies",
    "Ethnic Cuisine",
    "Food Blogs",
    "Food Photography",
    "Restaurant Reviews",
    "Food Festivals",
    "Street Food",
    "Comfort Food",
    "Meal Prep",
    "Gourmet Cooking",
    "Food Science",
    "Diet Plans",
    "Nutrition Tips",
    "Food Challenges",
    "Cooking Shows",
    "Food History"
  ],
  "Beauty & Style": [
    "Makeup",
    "Skincare",
    "Haircare",
    "Nail Art",
    "Fashion Trends",
    "Outfit Ideas",
    "Beauty Tutorials",
    "Product Reviews",
    "Fragrances",
    "Beauty Hacks",
    "DIY Beauty",
    "Salon Services",
    "Beauty Influencers",
    "Fashion Shows",
    "Wardrobe Essentials",
    "Seasonal Fashion",
    "Accessories",
    "Men's Grooming",
    "Street Style",
    "Red Carpet Fashion",
    "Sustainable Fashion",
    "Vintage Fashion",
    "Beauty Routines",
    "Anti-Aging Tips",
    "Personal Style",
    "Beauty Boxes",
    "Hairstyles",
    "Beauty Myths",
    "Fashion History",
    "Body Art"
  ],
  "Drama": [
    "TV Dramas",
    "Movie Dramas",
    "Theater Plays",
    "Dramatic Readings",
    "Soap Operas",
    "Historical Dramas",
    "Crime Dramas",
    "Romantic Dramas",
    "Legal Dramas",
    "Medical Dramas",
    "Political Dramas",
    "Family Dramas",
    "Teen Dramas",
    "Fantasy Dramas",
    "Thrillers",
    "Mystery Dramas",
    "War Dramas",
    "Epic Dramas",
    "Biographical Dramas",
    "Melodramas",
    "Period Dramas",
    "Psychological Dramas",
    "Supernatural Dramas",
    "Documentary Dramas",
    "Drama Reviews",
    "Drama Trailers",
    "Dramatic Monologues",
    "Drama Podcasts",
    "Independent Films",
    "Drama Festivals"
  ],
  "Learning": [
    "Online Courses",
    "Educational Videos",
    "Podcasts",
    "Reading Lists",
    "Language Learning",
    "Science",
    "Math",
    "History",
    "Geography",
    "Arts",
    "Literature",
    "Coding",
    "Technology",
    "Business",
    "Marketing",
    "Personal Finance",
    "Health",
    "Psychology",
    "Philosophy",
    "Political Science",
    "Economics",
    "Environmental Studies",
    "Sociology",
    "Astronomy",
    "Music Theory",
    "Film Studies",
    "Art History",
    "Public Speaking",
    "Writing Skills",
    "Study Tips"
  ],
  "Talent": [
    "Singing",
    "Dancing",
    "Playing Instruments",
    "Acting",
    "Comedy",
    "Magic Tricks",
    "Cooking",
    "Baking",
    "Painting",
    "Drawing",
    "Sculpting",
    "Crafts",
    "Photography",
    "Videography",
    "Writing",
    "Poetry",
    "Storytelling",
    "Public Speaking",
    "Sports",
    "Fitness",
    "Martial Arts",
    "DIY Projects",
    "Home Improvement",
    "Gardening",
    "Pet Training",
    "Coding",
    "Graphic Design",
    "Fashion Design",
    "Makeup Artistry",
    "Nail Art"
  ],
  "Sports": [
    "Soccer",
    "Basketball",
    "Baseball",
    "American Football",
    "Tennis",
    "Golf",
    "Running",
    "Cycling",
    "Swimming",
    "Boxing",
    "Wrestling",
    "Martial Arts",
    "Gymnastics",
    "Ice Hockey",
    "Cricket",
    "Rugby",
    "Volleyball",
    "Table Tennis",
    "Badminton",
    "Surfing",
    "Skateboarding",
    "Skiing",
    "Snowboarding",
    "Track and Field",
    "Rock Climbing",
    "Fishing",
    "Hiking",
    "Horseback Riding",
    "Archery",
    "Motorsports"
  ],
  "Auto": [
    "Cars",
    "Motorcycles",
    "Trucks",
    "Electric Vehicles",
    "Car Reviews",
    "Bike Reviews",
    "Auto Repair",
    "Car Maintenance",
    "Bike Maintenance",
    "Car Customization",
    "Motorbike Customization",
    "Racing",
    "Off-Roading",
    "Classic Cars",
    "Vintage Bikes",
    "Auto Shows",
    "Car Clubs",
    "Bike Clubs",
    "Driving Tips",
    "Safety Tips",
    "Road Trips",
    "Auto Accessories",
    "Motorbike Gear",
    "Eco-Friendly Vehicles",
    "Future Cars",
    "Concept Cars",
    "Auto News",
    "Motorbike News",
    "Test Drives",
    "Drag Racing"
  ],
  "Family": [
    "Parenting",
    "Pregnancy",
    "Baby Care",
    "Child Development",
    "Teenagers",
    "Family Activities",
    "Family Health",
    "Family Finances",
    "Home Organization",
    "Family Travel",
    "Holiday Planning",
    "Family Meals",
    "Family Games",
    "Educational Activities",
    "Family Traditions",
    "Family Therapy",
    "Work-Life Balance",
    "Sibling Relationships",
    "Adoption",
    "Foster Care",
    "Family Pets",
    "Grandparenting",
    "Family Fitness",
    "Home Safety",
    "Child Safety",
    "Family Budgeting",
    "Family Outings",
    "Family Technology",
    "Blended Families",
    "Single Parenting"
  ],
  "Fitness & Health": [
    "Workouts",
    "Nutrition",
    "Mental Health",
    "Yoga",
    "Meditation",
    "Running",
    "Cycling",
    "Swimming",
    "Weightlifting",
    "Pilates",
    "Aerobics",
    "Zumba",
    "CrossFit",
    "Home Workouts",
    "Gym Workouts",
    "Healthy Recipes",
    "Vitamins",
    "Supplements",
    "Fitness Apps",
    "Fitness Gear",
    "Personal Training",
    "Physical Therapy",
    "Injury Prevention",
    "Sports Medicine",
    "Healthy Habits",
    "Stress Management",
    "Sleep Tips",
    "Wellness Retreats",
    "Holistic Health",
    "Health Trends"
  ],
  "DIY & Life Hacks": [
    "Home Improvement",
    "Crafts",
    "Organization",
    "Cleaning",
    "Cooking Tips",
    "Gardening",
    "Tech Hacks",
    "Money Saving Tips",
    "Beauty Hacks",
    "Travel Tips",
    "Time Management",
    "Productivity",
    "Car Maintenance",
    "Pet Care",
    "Fashion Hacks",
    "Upcycling",
    "Recycling",
    "Furniture Makeover",
    "Decorating Tips",
    "Sewing",
    "Knitting",
    "Creative Projects",
    "Life Skills",
    "Office Hacks",
    "Study Tips",
    "Parenting Hacks",
    "Fitness Hacks",
    "Photography Tips",
    "Home Security",
    "Emergency Preparedness"
  ],
  "Arts & Crafts": [
    "Drawing",
    "Painting",
    "Sculpting",
    "Knitting",
    "Crocheting",
    "Sewing",
    "Embroidery",
    "Quilting",
    "Jewelry Making",
    "Paper Crafts",
    "Card Making",
    "Scrapbooking",
    "Origami",
    "Pottery",
    "Woodworking",
    "Glass Art",
    "Textile Art",
    "Mixed Media",
    "Digital Art",
    "Graphic Design",
    "Calligraphy",
    "Printmaking",
    "Collage",
    "Stamping",
    "DIY Home Decor",
    "Craft Fairs",
    "Craft Tutorials",
    "Art Supplies",
    "Art History",
    "Art Therapy"
  ],
  "Dance": [
    "Ballet",
    "Hip-Hop",
    "Contemporary",
    "Jazz",
    "Tap Dance",
    "Ballroom",
    "Salsa",
    "Tango",
    "Swing",
    "Breakdancing",
    "Folk Dance",
    "Modern Dance",
    "Lyrical",
    "Street Dance",
    "Latin Dance",
    "Dance Fitness",
    "Choreography",
    "Dance Competitions",
    "Dance Classes",
    "Dance Tutorials",
    "Dance Performances",
    "Dance Shows",
    "Dance History",
    "Dance Costumes",
    "Dance Music",
    "Dance Festivals",
    "Dance Therapy",
    "Dance Gear",
    "Dance Trends",
    "Dance Challenges"
  ],
  "Outdoors": [
    "Hiking",
    "Camping",
    "Fishing",
    "Hunting",
    "Birdwatching",
    "Rock Climbing",
    "Mountain Biking",
    "Trail Running",
    "Kayaking",
    "Canoeing",
    "Sailing",
    "Surfing",
    "Snowboarding",
    "Skiing",
    "Scuba Diving",
    "Snorkeling",
    "Wildlife Watching",
    "Nature Photography",
    "Outdoor Cooking",
    "Backpacking",
    "Orienteering",
    "Stargazing",
    "Outdoor Gear",
    "Outdoor Safety",
    "National Parks",
    "Eco-Tourism",
    "Survival Skills",
    "Outdoor Education",
    "Geocaching",
    "Outdoor Events"
  ],
  "Oddly Satisfying": [
    "ASMR",
    "Slime",
    "Kinetic Sand",
    "Cutting Soap",
    "Paint Mixing",
    "Power Washing",
    "Ice Crushing",
    "Bubble Wrap Popping",
    "Hydraulic Press",
    "Pimple Popping",
    "Cake Decorating",
    "Wood Turning",
    "Resin Art",
    "Glass Cutting",
    "Metal Forging",
    "Smoothie Pouring",
    "Color Sorting",
    "Tile Cutting",
    "Paint Pouring",
    "Clay Sculpting",
    "Sand Art",
    "Water Droplets",
    "Leaf Blowing",
    "Fabric Folding",
    "Pressure Cleaning",
    "Car Detailing",
    "Soap Making",
    "Knitting",
    "Rug Cleaning",
    "Calligraphy"
  ],
  "Home & Garden": [
    "Interior Design",
    "Landscaping",
    "Home Renovation",
    "Gardening Tips",
    "Houseplants",
    "Outdoor Decor",
    "DIY Projects",
    "Home Organization",
    "Cleaning Tips",
    "Home Security",
    "Sustainable Living",
    "Energy Efficiency",
    "Real Estate",
    "Smart Home",
    "Home Maintenance",
    "Furniture Restoration",
    "Kitchen Design",
    "Bathroom Design",
    "Living Room Ideas",
    "Bedroom Ideas",
    "Patio Ideas",
    "Balcony Gardening",
    "Vegetable Gardening",
    "Flower Gardening",
    "Herb Gardening",
    "Garden Tools",
    "Composting",
    "Pest Control",
    "Home Decor Trends",
    "Seasonal Decor"
  ],
};

class InterestDetailScreen extends StatefulWidget {
  final List<String> interestList;
  const InterestDetailScreen({
    super.key,
    required this.interestList,
  });

  @override
  State<InterestDetailScreen> createState() => _InterestDetailScreenState();
}

class _InterestDetailScreenState extends State<InterestDetailScreen> {
  void _onNextTap() {}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const FaIcon(
          FontAwesomeIcons.twitter,
          size: Sizes.size36,
        ),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: Sizes.size24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                "What do you want to see on Twitter?",
                style: TextStyle(
                  fontSize: Sizes.size36,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Gaps.v16,
              Text(
                "Select at least 3 interests to personalize your Twitter experience. They will be visible on your profile.",
                style: TextStyle(
                  fontSize: Sizes.size20,
                  color: Colors.grey.shade600,
                ),
              ),
              Gaps.v16,
              for (var interest in widget.interestList)
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Gaps.v16,
                    Container(
                      margin: const EdgeInsets.symmetric(
                        horizontal: Sizes.size5,
                      ),
                      height: Sizes.size1,
                      decoration: BoxDecoration(
                        color: Colors.grey.shade300,
                      ),
                    ),
                    Gaps.v16,
                    Text(
                      interest,
                      style: const TextStyle(
                          fontSize: Sizes.size28,
                          fontWeight: FontWeight.w600,
                          color: Colors.black),
                    ),
                    Gaps.v16,
                    SizedBox(
                      height: Sizes.size48,
                      child: ListView(
                        scrollDirection: Axis.horizontal,
                        children: [
                          for (var detail in interestDetails[interest]!)
                            Container(
                              margin: const EdgeInsets.only(
                                left: Sizes.size5,
                              ),
                              child: InterestDetailButton(interest: detail),
                            ),
                        ],
                      ),
                    ),
                    Gaps.v16,
                  ],
                ),
            ],
          ),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        height: Sizes.size72,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: Sizes.size24),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              GestureDetector(
                onTap: _onNextTap,
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 300),
                  padding: const EdgeInsets.symmetric(
                      horizontal: Sizes.size16, vertical: Sizes.size6),
                  decoration: BoxDecoration(
                    color: Colors.black,
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: const Text(
                    "Next",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: Sizes.size14,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
